dataset:
  simulated:
    n: [16384]
    d1: [400]
    d2: [400]
    iid: [true, false]
    n_blocks: [16]
    noise: [0.1]

solver:
  all-reduce:
    n_workers: [16]
    batch_size: [4, 32]
    lr: [1e-3]
    moments: [false, true]
  ef21:
    n_workers: [16]
    batch_size: [4, 32]
    lr: [1e-3]
    compressor: ["top-1", "top-10", "power-1", "power-10"]
  ef:
    n_workers: [16]
    batch_size: [4, 32]
    lr: [1e-3]
    compressor: ["top-1", "top-10", "power-1", "power-10"]
  pairwise:
    n_workers: [16]
    batch_size: [4, 32]
    lr: [1e-3]
    moments: [false]
  sgp:
    n_workers: [16]
    batch_size: [4, 32]
    lr: [1e-3]
    overlap: [0, 1]
  local:
    n_workers: [16]
    batch_size: [4, 32]
    lr: [1e-3]
    merge_every: [1]
    moments: [false, true]
  slowmo:
    n_workers: [16]
    batch_size: [4, 32]
    lr: [1e-3]
    merge_every: [4]
    slow_momentum: [0.6]
  adaslowmo:
    n_workers: [16]
    batch_size: [4, 32]
    lr: [1e-3]
    merge_every: [4]


n_repetitions: 1
timeout: 400