dataset:
  simulated:
    n: [16384]
    d1: [2000]
    d2: [2000]
    iid: [true, false]
    n_blocks: [16]
    noise: [0.]

solver:
  all-reduce:
    n_workers: [16]
    batch_size: [32]
    lr: [1e-2]
    moments: [false]
  pairwise:
    n_workers: [16]
    batch_size: [32]
    lr: [1e-2]
    moments: [false]
  local:
    n_workers: [16]
    batch_size: [32]
    lr: [1e-2]
    merge_every: [1]
    moments: [false]

n_repetitions: 1
timeout: 60